### ISSUE TITLE
oak-chunk-update: "sequence item 0: expected string, long found"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shlomi-noach/openarkkit#40]
```
What steps will reproduce the problem?
1. oak-chunk-update --verbose  --database=tipsfora_myimobitrax  --user=root 
--ask-pass  --socket=/var/lib/mysql/mysql.sock  --execute="DELETE FROM 
myimobitrax.mt_click where click_time <1412060400 and OAK_CHUNK(mt_click)"

What is the expected output? What do you see instead?

- Checking for UNIQUE columns on myimobitrax.mt_click, by which to chunk
-- Table locked READ
-- camp_id,click_time,click_id (min, max) values: ([12L, 1404201757L, 
18792867L], [1290L, 1415419358L, 45645222L])
-- Table unlocked
sequence item 0: expected string, long found


What version of the product are you using? On what operating system?
openark-kit-196-1.noarch.rpm (tried 170 and 180 - the same results)
Centos6.6
python 2.6.6

Please provide any additional information below.

Thank you,
Vitaly


```

Original issue reported on code.google.com by `linux...@gmail.com` on 8 Nov 2014 at 9:04

**Comment by jeremycohensolal** [comment]
I meet the same problem... the tool doesn't do the job :(

**Comment by jeremycohensolal** [comment]
I found a way of bypassing:

I had the problem when explicitely supplying --force-chunking-column=idTransaction

but after auditing the code... it is possible (but not documented i think...) to specify a type...

So by using `--force-chunking-column=idTransaction:integer` ... it works

It should be easy to fix this problem, i think than here: https://github.com/shlomi-noach/openarkkit/blob/master/openarkkit/src/oak/oak-chunk-update.py#L288 the variable "unique_key_type" is null...

The stack trace:

```
Traceback (most recent call last):
  File "/usr/bin/oak-chunk-update", line 675, in <module>
    chunk_update()
  File "/usr/bin/oak-chunk-update", line 609, in chunk_update
    act_data_pass(first_data_pass_query, rest_data_pass_query, "Performing chunks")
  File "/usr/bin/oak-chunk-update", line 535, in act_data_pass
    verbose("%s range (%s), (%s), progress: N/A" % (description, ",".join(unique_key_range_start_values), ",".join(unique_key_range_end_values)))
TypeError: sequence item 0: expected string, long found
sequence item 0: expected string, long found
```
